#pragma once

#include "IADC.h"
#include "IGPIO.h"
#include "II2C.h"
#include "ISPI.h"
#include "IStorage.h"
#include "IUART.h"
#include "ISysTimer.h"
#include "IRCIN.h"
#include "IRCOUT.h"
#include "IAsyncWorker.h"

#include "IAccelerometer.h"
#include "IBarometer.h"
#include "IBatteryVoltage.h"
#include "IFlow.h"
#include "IGPS.h"
#include "IGyro.h"
#include "ILED.h"
#include "IMagnetometer.h"
#include "IRawDevice.h"
#include "IRGBLED.h"
#include "IRangeFinder.h"