#pragma once

// LMX2572 as a basic frequency synthesizer
// only basic function implemented: ref&output freqency and output power config, lock detect.
// default regs generated by TICS Pro
// hardware: 2nd order loop filter in datasheet.
// default configuration: 40Mhz single ended ref in, 23.4375Mhz output on RFoutA

#include <HAL/Interface/ISPI.h>
#include <HAL/Interface/IGPIO.h>

class LMX2572
{
public:
	LMX2572();
	~LMX2572();
	int init(HAL::ISPI *spi, HAL::IGPIO *cs);
	int set_ref(uint32_t ref_freq, bool doubler, int pre_R, int multiplier, int R);
	int set_freq(uint64_t freq);
	int set_output(bool enable, int power);
	bool is_locked();

protected:
	void write_reg(uint8_t address, uint16_t data);
	uint16_t read_reg(uint8_t address);
	HAL::ISPI *spi;
	HAL::IGPIO *cs;

	uint32_t pfd_freq;
	uint16_t regs[126];
};
